#### general settings
name: ntire20_sr
use_tb_logger: true
model: srgan
distortion: sr
scale: 4
gpu_ids: [6,7]

#### datasets
datasets:
  train:
    name: train
    mode: LQGT
    aug: noise
    noise_data: ./dataset/DF2K/Corrupted_noise/
    dataroot_GT: ./dataset/DF2K/generated/tdsr/HR
    dataroot_LQ: ./dataset/DF2K/generated/tdsr/LR
    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 16
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: val
    mode: LQGT
    dataroot_GT: ./dataset/ntire20/track1-valid-gt
    dataroot_LQ: ./dataset/ntire20/track1-valid-input

#### network structures
network_G:
  which_model_G: RRDBNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23

network_D:
  which_model_D: NLayerDiscriminator
  in_nc: 3
  nf: 64
  nlayer: 3

#### path
path:
  pretrain_model_G: ./premodel/RRDB_PSNR_x4.pth
  strict_load: false
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.999
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.999
  lr_scheme: MultiStepLR

  niter: 150000
  warmup_iter: -1  # no warm up
  lr_steps: [10000, 30000, 50000, 80000, 120000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: 0.01 #0.01  # 1
  feature_criterion: l1
  feature_weight: 1 #1
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 5e-3
  cr_weight: !!float 1e-3 #0.001

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: !!float 2.5e3

#### logger
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 2.5e3
